version: "3.9"
services:
  spacezbe:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - EMAIL_HOST_USER=spacedjango5@gmail.com
      - EMAIL_HOST_PASSWORD=12345678asd
      - DJANGO_DB_NAME=postgres
      - DJANGO_SU_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_SU_EMAIL=dangnk@my.company
      - DJANGO_SU_PASSWORD=postgres
      - DJANGO_DB_PASSWORD=postgres
      - DJANGO_DB_HOST=127.0.0.1:5432
    command: 
      - sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate        
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
