# Generated by Django 3.1.13 on 2021-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublic',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
