# Generated by Django 3.1.13 on 2021-11-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20211107_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cards.userpublic'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='cards.userpublic'),
        ),
        migrations.AlterField(
            model_name='socials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='cards.userpublic'),
        ),
    ]
