# Generated by Django 3.1.13 on 2021-11-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20211107_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.user'),
            preserve_default=False,
        ),
    ]
