# Generated by Django 3.1.13 on 2021-11-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpublic',
            name='avatars',
        ),
        migrations.RemoveField(
            model_name='userpublic',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
