# Generated by Django 3.1.13 on 2021-11-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_lo_titletruoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='lo_titleTruoc',
            field=models.TextField(blank=True, default='300,300', null=True),
        ),
    ]
