# Generated by Django 3.1.13 on 2021-11-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20211116_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lo_nameTruoc',
            field=models.TextField(blank=True, default='300,300', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='lo_rgbnameTruoc',
            field=models.TextField(blank=True, default='0,0,0', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='lo_rgbtitleTruoc',
            field=models.TextField(blank=True, default='0,0,0', null=True),
        ),
    ]
