# Generated by Django 3.1.13 on 2021-11-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20211116_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lo_nameName',
            field=models.TextField(blank=True, default='200,200', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='lo_rgbnameName',
            field=models.TextField(blank=True, default='245,87,108', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='lo_rgbtitleName',
            field=models.TextField(blank=True, default='245,87,108', null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='lo_titleName',
            field=models.TextField(blank=True, default='200,200', null=True),
        ),
    ]
