# Generated by Django 3.1.13 on 2021-11-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroudCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('css', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default=None, upload_to='background/%Y/%m')),
            ],
        ),
    ]
