# Generated by Django 3.1.13 on 2021-11-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_backgroudcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroudcard',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background/%Y/%m'),
        ),
    ]
