# Generated by Django 3.1.13 on 2021-11-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20211118_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpublic',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='userpublic',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='userpublic',
            name='user',
        ),
    ]
