# Generated by Django 3.1.13 on 2021-11-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_auto_20211123_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatars', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('profile_title', models.CharField(max_length=250)),
                ('decripttion', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data2', to='cards.userpublic')),
            ],
        ),
    ]
