# Generated by Django 3.1.13 on 2021-11-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_data2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data2',
            old_name='profile_title',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='data2',
            name='avatars',
        ),
        migrations.RemoveField(
            model_name='data2',
            name='decripttion',
        ),
        migrations.AddField(
            model_name='data2',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Data3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatars', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m')),
                ('profile_title', models.CharField(max_length=250)),
                ('decripttion', models.TextField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data3', to='cards.userpublic')),
            ],
        ),
    ]
