# Generated by Django 3.1.13 on 2021-11-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_auto_20211123_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data2',
            name='username',
        ),
        migrations.RemoveField(
            model_name='data3',
            name='username',
        ),
        migrations.AddField(
            model_name='userpublic',
            name='data2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.data2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpublic',
            name='data3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.data3'),
            preserve_default=False,
        ),
    ]
