# Generated by Django 3.1.13 on 2021-11-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_auto_20211123_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpublic',
            name='data2',
        ),
        migrations.RemoveField(
            model_name='userpublic',
            name='data3',
        ),
        migrations.AddField(
            model_name='data2',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data2', to='cards.userpublic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data3',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data3', to='cards.userpublic'),
            preserve_default=False,
        ),
    ]
