# Generated by Django 3.1.13 on 2021-11-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_auto_20211123_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data3',
            name='avatars',
        ),
        migrations.AddField(
            model_name='userpublic',
            name='avatars',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
