# Generated by Django 3.1.13 on 2021-11-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_auto_20211124_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublic',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
