# Generated by Django 3.1.13 on 2021-11-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_userpublic_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublic',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpublic',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='background/%Y/%m'),
        ),
    ]
