# Generated by Django 3.1.13 on 2021-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_auto_20211124_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
